### ISSUE TITLE
Upgrading to latest python-markdown breaks tests

### ISSUE THREAD

**Issue by eykd** [Crossway/antimarkdown#5]
While setting up Travis-CI, I noticed that upgrading to `Markdown==2.6.8` causes some of the tests to break. There must be some behavior changes between the 2.5.x and 2.6.x. series.

**Comment by ryanmrubin** [comment]
I was messing with this, and reproduced the failures if I only upgraded `Markdown`, but not if I also upgraded `html5lib`. There's a comment in there that the 7-9s version of `html5lib` is required for html5tidy, but is that true, since upgrading it does not cause any tests to fail and indeed fixes the test failures caused by upgrading `markdown`?

**Comment by ryanmrubin** [comment]
NEVER MIND my virtualenv was in a weird and not-reproducible state. Not sure what happened there.

**Comment by dwickwire** [comment]
Is this still an issue or was it closed by #8

**Comment by ryanmrubin** [comment]
This is still an issue. One test fails on the new version of Markdown. I was thinking about looking into it today.
